<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ucl</string>
	</array>
	<key>name</key>
	<string>uclid</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\bif\b|\belse\b|\bwhile\b|\bcase\b|\besac\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bvar\b|\binput\b|\boutput\b|\bsharedvar\b</string>
			<key>name</key>
			<string>variable</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bassert\b|\bassume\b|\binvariant\b|\baxiom\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\binit\b|\bnext\b|\bcontrol\b</string>
			<key>name</key>
			<string>markup.bold</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\brequires\b|\bensures\b|\bmodifies\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\breturns\b|\binline\b|\bnoinline\b</string>
			<key>name</key>
			<string>storage.modifier</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bmodule\b|\btype\b|\bprocedure\b|\bdefine\b|\bfunction\b|\bsynthesis\b</string>
			<key>name</key>
			<string>support.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bcall\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\binduction\b|\bcheck\b|\bprint_results\b|\bprint_cex\b|\bverify\b|\bbmc\b|\bunroll\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\be[A-Z]\w*\b</string>
			<key>name</key>
			<string>string.regexp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\binteger\b|\bboolean\b|\benum\b|\brecord\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\w*V\b</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\btrue\b|\bfalse\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.p</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.p</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ucl</string>
</dict>
</plist>
